name: Update Prettier
"on":
  push:
    branches:
      - renovate/prettier-*
jobs:
  update_prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.OCTOKIT_APP_ID }}
          private-key: ${{ secrets.OCTOKIT_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci
      - run: npm run lint:fix
      - uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          title: Prettier updated
          body: An update to prettier required updates to your code.
          branch: ${{ github.ref }}
          commit-message: "style: prettier"
