name: Update Prettier
"on":
  push:
    branches:
      - dependabot/npm_and_yarn/prettier-*
jobs:
  update_prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          version: 12
      - run: npm ci
      - run: "npm run lint:fix"
      - uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          title: Prettier updated
          body: An update to prettier required updates to your code.
          branch: "${{ github.ref }}"
          commit-message: "style: prettier"
